### ISSUE TITLE
Allow initialisation prior when defining model in Julia

### ISSUE THREAD

**Issue by sebapersson** [sebapersson/PEtab.jl#123]
When generating startguesses for parameter estimation it can be relevant to sample these from the prior, instead of from the uniform interval upper and lower bounds.

I propose the following:

```julia
c1 = PEtabParameter(:c1, prior=Normal(0, 2), sample_from_prior=true)
```

where `sample_from_prior=true `means that when generating the startguesses for parameter `c1` startguesses are taken from the prior. As this is relevant for the Catalyst integration, does it look good @TorkelE ?

**Comment by TorkelE** [comment]
Having this makes a lot of sense. I imagine one might want to have this as default option, or possibly an option in `generate_startguesses` or `calibrate_model_multistart` to automatically turn this on for all parameters (in case one have like 10 and want this for all)?

**Comment by sebapersson** [comment]
Having it also as an option in `generate_startguesses` definitely makes sense. 

When thinking on it closer, having it as default also sounds good - because if we have a priors then sampling to far away from them is not going to help with parameter estimation.

I will then do it like this, for `generate_startguesses` and `calibrate_model_multistart` I will have `sample_from_prior=true` - where `true` here means sample from priors for all parameters that have `sample_from_prior=true` for their  `PEtabParameter` - then for `PEtabParameter` I will have `sample_from_prior=true` by default. Then if the user wants to fully turn of sampling from prior they set `sample_from_prior=false` in `generate_startguesses` or `calibrate_model_multistart`, while if they want to do it for a few parameters they can do it in `PEtabParameter`.

What do you think?

**Comment by TorkelE** [comment]
That sounds ideal 👍
