### ISSUE TITLE
`get_odesol` returns solution where everything is zero

### ISSUE THREAD

**Issue by TorkelE** [sebapersson/PEtab.jl#148]
I am developing a function for https://github.com/sebapersson/PEtab.jl/issues/100, and want to use `get_odesol` in the process of doing so. However, it seems to output something that is uniformly 0?

Example:
```julia
using Catalyst, PEtab

rn = @reaction_network begin
    kB, S + E --> SE
    kD, SE --> S + E
    kP, SE --> P + E
end

u0 = [:E => 1.0, :SE => 0.0, :P => 0.0]
p_true = [:kB => 1.0, :kD => 0.1, :kP => 0.5]

# Simulate data.
using OrdinaryDiffEq
oprob_true = ODEProblem(rn, [:S=>1.0; u0], (0.0, 10.0), p_true)
data_sol = solve(oprob_true, Tsit5(); saveat=1.0)
times, data = data_sol.t[2:end], (0.8 .+ 0.4*rand(10)) .* data_sol[:P][2:end]

# Plot simulated data.
using Plots
plot(data_sol; idxs=:P, label="True solution", lw=8)
plot!(times, data; label="Measurements", seriestype=:scatter, ms=6, color=:blue)

# Make PETab problem.
begin
    @unpack P = rn
    obs_P = PEtabObservable(P, 0.5)
    observables = Dict("obs_P" => obs_P)

    par_kB = PEtabParameter(:kB)
    par_kD = PEtabParameter(:kD)
    par_kP = PEtabParameter(:kP)
    params = [par_kB, par_kD, par_kP]

    using DataFrames
    measurements = DataFrame(obs_id="obs_P", time=times, measurement=data)

    petab_model = PEtabModel(rn, observables, measurements, params; state_map=u0)
    petab_problem = PEtabODEProblem(petab_model)
end

using Optim
p0 = generate_startguesses(petab_problem, 1)
res = calibrate_model(petab_problem, p0, IPNewton())

sol_fetched = get_odesol(res, petab_problem)
plot!(sol_fetched; idxs=:P, label="Fetched solution", lw=8)

oprob_fitted = remake(oprob_true; p=get_ps(res, petab_problem))
fitted_sol = solve(oprob_fitted, Tsit5())
plot!(fitted_sol; idxs=:P, label="Fitted solution", lw=8)
```
![image](https://github.com/sebapersson/PEtab.jl/assets/18099310/b7d625f7-4761-4a3f-aaf3-d0cfd4500ecc)

(here, the green is using `get_odesol`, the purple is with `get_ps` and then simulate using it)

**Comment by TorkelE** [comment]
Actually, think there's an error in the example, all good.

**Comment by sebapersson** [comment]
Thanks for noticing the error in the code. In addition, something that can cause problems is that it is important to remember the initial values which can be obtained via `get_u0`:

```julia
oprob_fitted = remake(oprob_true; p=get_ps(res, petab_problem), u0=get_u0(res, petab_problem))
fitted_sol = solve(oprob_fitted, Tsit5())
plot!(fitted_sol; idxs=:P, label="Fitted solution", lw=8)
```

As for #100 in the PEtabODEProblem there is a function named `petab_problem.compute_simulated_values(x0)` (which is lacking from the docs which I should fix), which for a parameter vector x0 computes the simulated values (with correct observable values, transformation etc...) following the order that can be found in the internal `MeasurementsInfo` struct, which also stores simulation conditions ids. 

So for #100 maybe the best solution would be to just use `petab_problem.compute_simulated_values(x0)`, and then to get the observable data just use the data in `MeasurementsInfo`, this would also require to put `MeasurementsInfo` into the `PEtabODEProblem` struct (it is not a part of it currently, but should)
