### ISSUE TITLE
When simulating model with conditions with different initial conditions, input `ReactionSystem` gets mutated (parameters added)

### ISSUE THREAD

**Issue by TorkelE** [sebapersson/PEtab.jl#155]
Basically, in a case, the input `ReactionSystem` model gets mutated. See this minimal example:
```julia
using Catalyst, PEtab, DataFrames

# Model.
rs = @reaction_network begin
    (k1, k2), X1 <--> X2 
end

# Known initial conditions.
u0 = [:X1 => 1.0]

# Observables.
@unpack X1 = rs
obs_X1 = PEtabObservable(X1, 0.5)
observables = Dict("obs_X1" => obs_X1)

# Parameters.
par_k1 = PEtabParameter(:k1)
par_k2 = PEtabParameter(:k2)
params = [par_k1, par_k2]

# Conditions.
c1 = Dict(:X2 => 1.0)
c2 = Dict(:X2 => 2.0)
simulation_conditions = Dict("c1" => c1, "c2" => c2)

# Measurements
using DataFrames
m_c1 = DataFrame(simulation_id = "c1", obs_id="obs_X1", time=[1.0, 2.0, 3.0], measurement=[1.1, 1.2, 1.3])
m_c2 = DataFrame(simulation_id = "c2", obs_id="obs_X1", time=[1.0, 2.0, 3.0], measurement=[1.2, 1.4, 1.6])
measurements = vcat(m_c1, m_c2)

# Make optimisation problem.
petab_model = PEtabModel(rs, simulation_conditions, observables, measurements, params; state_map=u0)
petab_problem = PEtabODEProblem(petab_model)

parameters(rs) # returns [k1,  k2, __init__X2__]
```

I guess it makes sense internally that the initial condition becomes a parameter. However, it seems distinctly un-good that the model the user provided is mutated (especially when they are not told about it). A simple solution might be to simply use a `deepcopy` of the model, which is created first thing when it is sent to `PEtabModel`. More elegant solutions might be possible though.

**Comment by sebapersson** [comment]
This is very observant :) 

It makes a lot of sense internally to mutate the model. When we compute the gradient for some methods we must be able to compute the `Jacobian` with respect to model parameters. These parameter can sometimes be initial values, and by mutating the model it is easy to get a correct Jacobian. 

I agree that it is un-good to mutate without telling the user (this was less of a problem when originally we only accepted SBML-models). As the user does not really need to have a model where it is easy to compute the Jacobian I think a good solution might be:

* As you suggested use `deepcopy` and in `PEtabModel` store both the original and internally used model (with this we only need to compile a new `ReactionSystem` once). Lastly, a small hack to `get_p` and `get_u0` will have to be added, as for these util functions we should assume that the user mean the original system.

What do you think?

**Comment by TorkelE** [comment]
yes, that sounds like a good solution

**Comment by TorkelE** [comment]
Thanks :+1:
