### ISSUE TITLE
Warning of MTK changes, states being renamed unknowns

### ISSUE THREAD

**Issue by TorkelE** [sebapersson/PEtab.jl#166]
Not sure if you are aware, but some changes are coming to MTK, probably in the next few weeks. This should be a summary: https://github.com/SciML/ModelingToolkit.jl/issues/2262

We are trying to deal with these at Catalyst. Some things will also affect PEtab, might be useful to be aware of (if you aren't already). Notably "states" will now be called "unknown". This might cause some bugs. Also, it might make sense to rename e.g. `state_map` to `unknown_map`.

**Comment by sebapersson** [comment]
Thanks for the notice. And yes, MTK v9 likely will break some things. It is also that SciMLStructures Tunable parameters will soon be ready, and those should also be used by PEtab.jl.

And renaming would definitely make sense. Along with get functions #157 there will be some changes to the API. So I think that along with MTK it will likely be worthwhile to make changes for the API, and create a new major version. So besides #157 any additional changes you think would be good for a new major release?

**Comment by TorkelE** [comment]
Do we know what Tunable parameters are and how they would actually change things? Parameters can already be designated as "Tunable" via metadata, but that is just adding a tag to them.

One thing I would (re)consider is permitting Symbol expressions when creating `PEtabObservables`, e.g.
```julia
obs_X = PEtabObservable(:X, 0.5)
```
The reason is that Catalyst now (in dev branch awaiting v14) has full support for observables, and for situations where expressions of species/variables/parameters are formed, I want to move towards recommending these.

E.g. currently this workflow:
```julia
two_state_model = @reaction_network begin
    (k1,k2), X1 <--> X2
end
@unpack X1, X2 = two_state_model
obs_X = PEtabObservable(X1 + X2, 0.5)
```
would then be
```julia
two_state_model = @reaction_network begin
    @observables X ~ X1 + X2
    (k1,k2), X1 <--> X2
end
@unpack X = two_state_model
obs_X = PEtabObservable(X, 0.5)
```
and could be simplified to
```julia
two_state_model = @reaction_network begin
    @observables X ~ X1 + X2
    (k1,k2), X1 <--> X2
end
obs_X = PEtabObservable(:X, 0.5)
```

Hopefully, Observables should mean that `@unpack` is never required (expect for very niche circumstances)

**Comment by sebapersson** [comment]
Tunable parameters will for example allow SciMLSensitity to know if certain parameters are constant or not. This can be very useful when for example doing adjoint sensitivity analysis as current the gradient is actually computed for the whole `oprob.p`, similar holding when computing the gradient for forward methods (here it will have quite the impact on performance). Hopefully it might also mean that PEtab.jl has to do less index operations behind the scenes. In the long run, it might make it easier to integrate PEtab.jl with frameworks as Diffractor and Enzyme.

And the suggestion for observable sounds great, and yes I think this would definitely make it easier for the user.

**Comment by sebapersson** [comment]
A bit overdue, but with #211 the update to Catalyst v14 and ModelingToolkit v13 is done. I have yet to add support for `@observables` which I think would be a great addition. But I also want to push out v3, so I will open a separate issue for `@observables` and hopefully it should be added soon.
