### ISSUE TITLE
PEtab fails with DataInterpolations

### ISSUE THREAD

**Issue by langestefan** [sebapersson/PEtab.jl#208]
I have the following model:

<details model>
  <summary><i>model</i></summary>

```julia
using ModelingToolkit
using ModelingToolkitStandardLibrary.Blocks
using DataInterpolations
using OrdinaryDiffEq
using DataFrames
using PEtab
using QuasiMonteCarlo
using Distributions
using Optim


function model_Ti(input_funcs::Dict)
    @parameters C_i R_ia A_w Ti_0
    @variables t T_i(t) T_a(t) P_h(t) P_s(t)
    D = Differential(t)

    @named T_a_out = TimeVaryingFunction(input_funcs[:T_a])
    @named P_h_out = TimeVaryingFunction(input_funcs[:P_h])
    @named P_s_out = TimeVaryingFunction(input_funcs[:P_s])

    systems = [T_a_out, P_h_out, P_s_out]

    # define model ODE system
    eqs = [
        C_i * D(T_i) ~ (1 / R_ia) * (T_a - T_i) + A_w * P_s + P_h
    ]

    # define inputs 
    inputs = [
        T_a ~ T_a_out.output.u
        P_h ~ P_h_out.output.u
        P_s ~ P_s_out.output.u
    ]
    append!(eqs, inputs)

    @named sys = ODESystem(eqs, t; systems=systems, defaults=Dict(T_i => Ti_0))
    return sys
end


function create_model(model_type::Symbol, input_funcs::Dict)
    model_fn = Symbol(join(String.([:model_, model_type])))
    model = getfield(ThermalFit, model_fn)(input_funcs)
    return model
end


function estimate_model_params(model_type::Symbol, df::DataFrame)
    # create input input functions
    T_a = DataInterpolations.LinearInterpolation(df.T_a, df.t_hour)
    P_h = DataInterpolations.LinearInterpolation(df.P_h, df.t_hour)
    P_s = DataInterpolations.LinearInterpolation(df.P_s, df.t_hour)

    # create model
    input_funcs = Dict(:T_a => T_a, :P_h => P_h, :P_s => P_s)
    model = create_model(model_type, input_funcs)
    model = structural_simplify(model)

    @unpack T_i = model
    @parameters sigma

    # observables 
    obs_T_i = PEtabObservable(T_i, sigma, transformation=:lin)
    observables = Dict(
        "obs_T_i" => obs_T_i
    )

    # parameters to estimate: C_i R_ia A_w Ti_0
    _C_i = PEtabParameter(:C_i, lb=1e-3, ub=1e1, scale=:log10)
    _R_ia = PEtabParameter(:R_ia, lb=1e-3, ub=1e1, scale=:log10)
    _A_w = PEtabParameter(:A_w, lb=1e-3, ub=1e1, scale=:log10)
    _Ti_0 = PEtabParameter(:Ti_0, lb=10.0, ub=30.0, scale=:log10)
    parameters = [_C_i, _R_ia, _A_w, _Ti_0]

    # the measurement data should be organized as a DataFrame in the following format: 
    # simulation_id (str)	obs_id (str)	time (float)	measurement (float)
    measurements = vcat([
        DataFrame(
            obs_id=repeat(["obs_$(var)"], nrow(df)),
            time=df.t_hour,
            measurement=df[!, var]
        )
        for var in ["T_i"]
    ]...)

    # define petab model 
    petab_model = PEtabModel(model,
        observables,
        measurements,
        parameters,
        verbose=false
    )

    # define petab problem
    osolver = ODESolver(AutoVern7(Rodas5P()))
    petab_problem = PEtabODEProblem(petab_model; verbose=true, ode_solver=osolver)

    # calibrate model
    # res = calibrate_model_multistart(
    #     petab_problem,
    #     IPNewton(),
    #     10,
    #     "./dump",
    #     options=Optim.Options(iterations=200)
    # )
    # p0 = generate_startguesses(petab_problem, 1,
    #     sampling_method=QuasiMonteCarlo.SobolSample())

    p0 = [1.0, 1.0, 1.0, df.T_i[1]]

    # @show p0
    res = calibrate_model(
        petab_problem,
        p0,
        Optim.IPNewton(),
        options=Optim.Options(iterations=200),
    )

    return res
end
```

</details>

I have used here DataInterpolations to create a function from discrete data which is then passed into the `ODESystem`. 

Trying to solve the MTK ODEProblem from `oprob = petab_problem.ode_problem` gives:

> Cannot extrapolate as `extrapolate` keyword passed was `false`
> 
> Stacktrace:
>   [1] _interpolate
>     @ C:\Users\lange\.julia\packages\DataInterpolations\2GasK\src\interpolation_methods.jl:2 [inlined]

And computing the cost also fails with:
```julia
x = petab_problem.θ_nominalT
petab_problem.compute_cost(x)
```

> MethodError: Cannot `convert` an object of type Nothing to an object of type Real

[test_data.csv](https://github.com/user-attachments/files/17128765/test_data.csv)

**Comment by sebapersson** [comment]
Thanks for reporting! 

Will take a look this week and see if I can find what happens in PEtab for this model.

**Comment by langestefan** [comment]
Thanks a lot for taking the time to look at the issue, I have been very impressed with your responsiveness.

Just as a sanity check, I converted the `ODESystem` to a MTK `ODEProblem` and simulated it with some ballpark okay parameter estimates and that works fine:

```julia
function solve_ode_prob(sys::ODESystem, tspan::Tuple{Float64,Float64})
    @parameters C_i R_ia A_w
    parammap = [
        C_i => 10.0,
        R_ia => 7.0,
        A_w => 10.0,
    ]
    prob = ODEProblem(sys, 19.0, tspan, parammap)
    sol = solve(prob, Tsit5())
    return sol
end

tspan = (df_train.t_hour[begin], df_train.t_hour[end])
sol = solve_ode_prob(sys, tspan)
plot(sol, label="fit")
plot!(df_train.t_hour, df_train.T_i, label="data")
```

![image](https://github.com/user-attachments/assets/2b8e887c-2551-4cb6-acbb-92ca3a65a2dd)

**Comment by sebapersson** [comment]
Thanks! This is good news, then it probably means that there is just some minor issue inside PEtab.jl!

**Comment by langestefan** [comment]
Fingers crossed then :)

**Comment by sebapersson** [comment]
I found the problem, and I think it should be possible to handle it :)

So basically when you perform your simulations:

```julia
function solve_ode_prob(sys::ODESystem, tspan::Tuple{Float64,Float64})
    @parameters C_i R_ia A_w
    parammap = [
        C_i => 10.0,
        R_ia => 7.0,
        A_w => 10.0,
    ]
    prob = ODEProblem(sys, 19.0, tspan, parammap)
    sol = solve(prob, Tsit5())
    return sol
end

tspan = (df_train.t_hour[begin], df_train.t_hour[end])
sol = solve_ode_prob(sys, tspan)
plot(sol, label="fit")
plot!(df_train.t_hour, df_train.T_i, label="data")
```

We have that `tspan = (41.583333333333336, 83.25)`. Now, when PEtab.jl solves the `ODEProblem` it uses `tspan = [0.0, 83.25]`, now as there is no interpolation data at `t = 0` the extrapolation error is thrown by the `ODESolver`. You can reproduce this by running:

```julia
function solve_ode_prob(sys::ODESystem, tspan::Tuple{Float64,Float64})
    @parameters C_i R_ia A_w
    parammap = [
        C_i => 10.0,
        R_ia => 7.0,
        A_w => 10.0,
    ]
    prob = ODEProblem(sys, 19.0, tspan, parammap)
    sol = solve(prob, Tsit5())
    return sol
end

tspan = (0.0, df_train.t_hour[end])
sol = solve_ode_prob(sys, tspan)
plot(sol, label="fit")
plot!(df_train.t_hour, df_train.T_i, label="data")
```

So I think the most easy way for you to fix this problem is to have interpolation (`DataInterpolations`) data available at `t = 0`.

**Comment by langestefan** [comment]
That doesn't seem to fix the issue for me unfortunately.

However I also noticed that if I export `petab_prob.ode_problem` the `tspan` is wrong there as well:

```
ODEProblem with uType Vector{Float64} and tType Float64. In-place: true
timespan: (0.0, 5000.0)
u0: 1-element Vector{Float64}:
 0.0
```

`tspan` should be:
```
(df.t_hour[begin], df.t_hour[end]) = (0.0, 166.58333333333334)
```

**Comment by sebapersson** [comment]
When solving the ODE for the actual problem PEtab.jl uses another time-span, specifically `tspan = [0.0, 83.25]` (the `5000` is just a dummy time-point that is changed for the main simulation). If you could upload a `df` that also includes zero I could further check what goes wrong (might be that the best solution is to allow `extrapolate`, but, if possible we should avoid that)

**Comment by langestefan** [comment]
Sure, here is a new dataset:

[test_data.csv](https://github.com/user-attachments/files/17162394/test_data.csv)

If `tspan` is not the issue here, then the extrapolation error I get from solving `petab_prob.ode_problem` with `tspan = [0.0, 5000]` would also not tell us anything right?

With the above dataset:

```julia
p0 = generate_startguesses(petab_problem, 1,
      sampling_method=QuasiMonteCarlo.SobolSample())
```
Gives:
> MethodError: Cannot `convert` an object of type Nothing to an object of type Real

```julia
p0 = [1.0, 1.0, 1.0, df.T_i[1]]

res = calibrate_model(
    petab_problem,
    p0,
    Optim.IPNewton(),
    options=Optim.Options(iterations=200),
)
```

Gives:

> PEtabOptimisationResult
> --------- Summary ---------
> min(f)                = NaN
> Parameters esimtated  = 4
> Optimiser iterations  = 0
> Run time              = NaNs
> Optimiser algorithm   = Optim_IPNewton

**Comment by sebapersson** [comment]
You are correct, the `extrapolation` should not be the error. Something else is happening. I will try to look at this today (but can't make any promises as I am currently pushing for the PEtab v3 update and need to fix some minor things)

**Comment by sebapersson** [comment]
Actually looking at your code, you never define `sigma` as a `PEtabParameter`. This can actually case your error (as the code does not know which value to use for `sigma`, this should be caught by PEtab but alas)

**Comment by langestefan** [comment]
Wow, can't believe I missed that... that did the trick. Thanks a lot!
