### ISSUE TITLE
`obsid` argument ignored when plotting fitting results

### ISSUE THREAD

**Issue by langestefan** [sebapersson/PEtab.jl#228]
You can see it in the docs here: https://sebapersson.github.io/PEtab.jl/stable/pest_plot/#Plotting-the-Model-Fit

Both `E` and `P` are plotted while the argument only specifies `P`:
`plot(res, petab_prob; obsid=["obs_p"], cid="cond1", linewidth = 2.0)`

I observe the same thing in my own plotting code:
`plot(res, prob; obsid=["obs_T_i"], size=(1000, 600))`

![image](https://github.com/user-attachments/assets/9bbc05bb-5a07-48bd-9036-180462bc3094)

**Comment by sebapersson** [comment]
You are correct, thanks for noticing! 
This should be quite straightforward to patch, so will hopefully fix it today.

**Comment by sebapersson** [comment]
This was an easy fix, it should be `obsids` not `obsid` in the code.
