### ISSUE TITLE
Custom labels for observables + plotting observables + data for initial parameter

### ISSUE THREAD

**Issue by SteffenPL** [sebapersson/PEtab.jl#249]
Thanks for the great package! I'm using it for a new project, and it streamlines parameter optimisation quite a lot compared to the previous alternatives. 

Here are some small quality-of-life features which maybe could be added:

- Is it possible to rename PEObservables to give them a shorter label in plots?
![image](https://github.com/user-attachments/assets/6e170f2e-5073-4616-90a3-69f3e84fff1c)

- Similar, would it be possible to provide a plot function which shows for a PEProblem with the current parameters the observables computed via the model and and measurements? That way one could compare if the optimized solution really looks better than the initial guess.

Of course, all of these are minor things which might dillute the package. Feel free to close without any comment if it doesn't fit ;)   [clearly, all the plots could also produced without PETab.jl, so, it is not really a problem]

**Comment by sebapersson** [comment]
Thanks for the feedback, and happy to hear that the package makes your parameter estimation easier :)

As for your feedback, both are good points. In particular:

1. This should be doable already via `label` (as we are using a plot recipe you can use any `plot` keyword). You should be able to have `plot(...; label = ["label1", ...]`. Naturally this can be a bit cumbersome, so I think it should also be fair to have an option to show the `observable_id` instead in the legend.  What do you think?
2. So you mean to basically have something like `plot(x, ...)`, where `x` is a parameter vector? In this case, this is definitely something I can, and in hindsight, should add as a feature.

**Comment by sebapersson** [comment]
In version 3.4 you can now plot model fit for an average Vector, and you can also change the label in the plot to the observable id. You can find more details here https://sebapersson.github.io/PEtab.jl/stable/pest_plot/#Plotting-the-Model-Fit.
