### ISSUE TITLE
log2 scale on observableTransformation

### ISSUE THREAD

**Issue by max-de-rooij** [sebapersson/PEtab.jl#260]
I want to open a PEtab file which has log2 in the observableTransformation field in the observables file. Is it possible to add log2 to the valid transformations?

**Comment by sebapersson** [comment]
`log2` in not one of the valid transformations in the PEtab standard, but I can definitely see why it makes sense. Hence, I will add `log2` as a valid transformation in PEtab.jl (should be fixed this week), and I will try to also incorporate `log2` into the PEtab standard.

**Comment by max-de-rooij** [comment]
Thank you @sebapersson [this](https://www.ebi.ac.uk/biomodels/MODEL2306280002#Overview) is the model by the way, and if I change the `log2` in their observables file to `log` everything seems to work fine! Kudos!

**Comment by sebapersson** [comment]
With version 3.5 of PEtab.jl you can now import and use `log2` transformation.
