### ISSUE TITLE
Record parameter calibration values progress in output.

### ISSUE THREAD

**Issue by TorkelE** [sebapersson/PEtab.jl#64]
When calibrating a parameter set to data, and the optimizer iterates through parameter values: It would be useful to receive (if desired) the entire path in the output (and not just the best parameter set and loss function value). Either just all the loss function values or possibly the corresponding parameter sets as well. Is there a way to get this in the output? I feel that it is often useful to plot this to gain some idea of the performance of the optimising run.

**Comment by sebapersson** [comment]
I agree with you that this is useful information. Currently for the Optimizer's I wrap in PEtab.jl (Fides, Ipopt and Optim with box-constraints) for which I support multi-start optimization this information is not available. However, it is definitely possible to retrieve by writing a callback (how to write the callback function depends on the Optimization-package though so takes some time). 

Overall, if we would like to carry out the parameter-estimation in PEtab (which is probably a good idea as we can write a method that takes PEtabODEProblem and then calibrates the model) a better output struct from a single calibration run is likely needed, kind of something like:

```julia
struct PEtabOptimisationResult
     trace::Vector{Vector{Float64}} # Parameter vectors (if user wants to save them)
     cost_trace::Vector{Float64} # Likelihood value (if user wants to save them)
     n_iterations # Number of iterations optimiser
     cost_best # Best optimised value 
     p_best # Last parameter value 
     convergence_criteria # If user wants to 
     run_time # Always fun :)
end
```

Is there anymore output you think currently is needed? Otherwise I could take a look at writing a better optimization struct.

**Comment by TorkelE** [comment]
Would it make sense to have a single interface for when multi-start approaches are used? In these cases it would be useful to have all information for e.g. parameters plots:
![image](https://github.com/sebapersson/PEtab.jl/assets/18099310/566dd068-17fa-4aa1-a332-b2385128ddcc)

Then each start would have this kind of information, with the output structure containing these one a vector, as weöö as the best parameter and its cost value?

**Comment by sebapersson** [comment]
You are thinking that we have a function like `perform_multistart_callibration(petab_problem, optimizer_alg)` which then outputs a struct-like?

```julia
struct PEtabMultistartOptimisationResult
     best_vector::Vector{Vector{Float64}} # Parameter vectors (if user wants to save them)
     best_cost::Vector{Float64} # Likelihood value (if user wants to save them)
     n_multistarts::Int
     run_results::Vector{PEtabOptimisationResult} # See above
end
```
From a struct like this it would then be easy to write a function for generating the plot above. If something like this looks like a good format I can code a prototype.

**Comment by TorkelE** [comment]
Yes, that looks ideal :)

**Comment by TorkelE** [comment]
Awsome! I hope to start on Catalyst documentation for this this weekend.

**Comment by TorkelE** [comment]
I think this is more or less solved now, but then, maybe it is not:

When running `calibrate_model_multistart`, the output is saved to a file, and a `PEtabMultistartOptimisationResult` optimisation struct is returned. We are now writing plotting functions that take a `PEtabMultistartOptimisationResult`, and it seems possible that these will be used as the input for other types of analysis. Would it make sense for `calibrate_model_multistart` to either
1. When(/if) the runs finish, save the `PEtabMultistartOptimisationResult` to the output folder as well.
2. Create a constructor `PEtabMultistartOptimisationResult(folderpath::String)` which for a given folder (to which `calibrate_model_multistart` wrote the results) return a `PEtabMultistartOptimisationResult`.
?
(I tried to see if this was already possible, but didn't find anything)

**Comment by sebapersson** [comment]
Sorry did not see the reply here. 

I think 2 is a good solution `PEtabMultistartOptimisationResult(folderpath::String)` - I basically have functionality for this and will add it.

**Comment by TorkelE** [comment]
Sounds great :)
