### ISSUE TITLE
For `calibrate_model`, by default use random initial guess?

### ISSUE THREAD

**Issue by TorkelE** [sebapersson/PEtab.jl#81]
Would it make sense to, for `calibrate_model`, if an initial parameter guess (`p0`) is not provided, simply randomly select one from within the bounds (and priors) of the parameters? It feels like this will typically be a random value, in which case providing functionality for it might be good.

**Comment by sebapersson** [comment]
Hmm, I am against this, as I would like `calibrate_model` to mimic most available optimizers that all require a start-guess to be generated. 

But it would be nice to to have functionality for start-guesses, so maybe a good solution would be to export the `generate_startguesses` function, and make it return a vector in case the user only wants 1 start-guess?

**Comment by TorkelE** [comment]
Consistency is probably best here, and a `generate_startguesses` should serve the same purpose as well.
