### ISSUE TITLE
Enable extraction of objective function

### ISSUE THREAD

**Issue by TorkelE** [sebapersson/PEtab.jl#82]
If it is not already possible, it would be useful to extract the objective function created by `PEtabModel` (and alter minimised using `calibrate_model`). It could then be used for various analyses using other tools

**Comment by sebapersson** [comment]
The objective function minimized is already available in the PEtabODEProblem. The cost, gradient and Hessian can all be accessed via;

```julia
petab_model = PEtabModel(path_yaml)
petab_problem = PEtabODEProblem(petab_model)
# Objective 
petab_problem.compute_cost(p)
# Gradient (inplace)
petab_problem.compute_gradient!(g, p)
# Hessian 
petab_problem.compute_hessian(H, p)
```

The parameter order in p is specified by `petab_problem.θ_names`, it is also the parameter order in `res.xmin`. There is also a function `remake_PEtab_problem` for fixating parameters, e.g. for profile-likelihood.

What do you mean with alter minimised?

**Comment by TorkelE** [comment]
Sounds good

(alter should have been later, clearly failed proof-reading properly)
