### ISSUE TITLE
In events documentation, the "Modifying Event Parameters for Different Simulation Conditions" section appear twice

### ISSUE THREAD

**Issue by TorkelE** [sebapersson/PEtab.jl#95]
These two sections are not identical, but still seem highly redundant.
https://sebapersson.github.io/PEtab.jl/dev/Julia_event/#Modifying-Event-Parameters-for-Different-Simulation-Conditions
https://sebapersson.github.io/PEtab.jl/dev/Julia_event/#Modifying-Event-Parameters-for-Different-Simulation-Conditions-2

**Comment by sebapersson** [comment]
I agree, the documentation would work well enough with only one of these sections, thanks for spotting!
